import React, { useState, useEffect, useRef } from 'react';
import { useSearchParams } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import { useAuth } from '../context/AuthContext';
import { GemReport } from '../types';
import { useReactToPrint } from 'react-to-print';
import { GemReportPrint } from '../components/GemReportPrint';
import { Search, Printer, AlertTriangle, ChevronRight, Loader2, FileText, User } from 'lucide-react';
import { motion } from 'motion/react';

export default function Reprint() {
  const { profile, isAdmin } = useAuth();
  const [searchParams] = useSearchParams();
  const [reportId, setReportId] = useState(searchParams.get('id') || '');
  const [report, setReport] = useState<GemReport | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const printRef = useRef<HTMLDivElement>(null);

  const handlePrint = useReactToPrint({
    contentRef: printRef,
    documentTitle: `Reprint_${report?.report_id}`,
  });

  const handleSearch = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!reportId) return;

    setLoading(true);
    setError(null);
    setReport(null);

    try {
      let query = supabase.from('gem_reports').select('*').eq('report_id', reportId).single();
      
      const { data, error: fetchError } = await query;

      if (fetchError) {
        setError('Report identifier not found in registry.');
        return;
      }

      // Authorization check (already enforced by RLS, but for UX):
      if (!isAdmin && profile && data.created_by !== profile.id) {
        setError('Authorization failed. Access restricted to record owner.');
        return;
      }

      setReport(data);
    } catch (err: any) {
      setError('System error occurred during archival retrieval.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (reportId) handleSearch();
  }, []);

  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      <header className="mb-12">
        <div className="flex items-center gap-2 mb-2">
          <ChevronRight size={16} className="opacity-40" />
          <span className="font-mono text-[10px] uppercase tracking-widest opacity-60">Archival Retrieval Module</span>
        </div>
        <h1 className="font-serif italic font-bold text-4xl">Reprint Certification</h1>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-12 mb-12">
        <div className="lg:col-span-1 border-r border-[#141414]/10 pr-8">
          <div className="bg-[#F5F5F0] border border-[#141414] p-6 shadow-[8px_8px_0px_0px_#141414]">
            <h3 className="font-mono text-[10px] uppercase tracking-widest opacity-60 mb-6 flex items-center gap-2">
              <Search size={14} /> Record Identification
            </h3>
            
            <form onSubmit={handleSearch} className="space-y-4">
              <div>
                <label className="block font-mono text-[9px] uppercase tracking-wider mb-2 opacity-50">Report Number</label>
                <input
                  required
                  type="text"
                  value={reportId}
                  onChange={(e) => setReportId(e.target.value)}
                  className="w-full px-4 py-3 bg-white border border-[#141414] focus:outline-none focus:ring-1 focus:ring-[#141414] font-mono text-xs uppercase"
                  placeholder="TSG-YYYYMMDD-XXXX"
                />
              </div>
              <button
                type="submit"
                disabled={loading}
                className="w-full bg-[#141414] text-[#E4E3E0] py-3 font-mono text-xs uppercase tracking-widest flex items-center justify-center gap-2 hover:bg-[#252525] transition-colors disabled:opacity-50"
              >
                {loading ? <Loader2 className="animate-spin" size={14} /> : 'Retrieve Record'}
              </button>
            </form>

            <div className="mt-8 pt-6 border-t border-[#141414]/10">
              <div className="flex items-center gap-2 mb-2 text-amber-600">
                <AlertTriangle size={14} />
                <span className="font-mono text-[9px] uppercase font-bold tracking-widest">Protocol Notice</span>
              </div>
              <p className="font-sans text-[11px] italic opacity-60 leading-relaxed">
                {isAdmin ? 
                  "Administrator access: Full reprint capabilities granted for all system records." : 
                  "Standard user access: Reprinting is restricted to certifications generated by your terminal identification."
                }
              </p>
            </div>
          </div>
        </div>

        <div className="lg:col-span-2">
          {error && (
            <motion.div 
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-red-50 border border-red-900/10 text-red-700 p-8 rounded shadow-sm text-center"
            >
              <AlertTriangle className="mx-auto mb-4 opacity-50" size={32} />
              <p className="font-mono text-xs uppercase tracking-widest font-bold mb-1">Retrieval Failed</p>
              <p className="font-sans text-sm italic">{error}</p>
            </motion.div>
          )}

          {!report && !error && !loading && (
            <div className="py-24 text-center opacity-20 italic flex flex-col items-center">
              <FileText size={64} className="mb-4" />
              <p className="font-mono text-xs uppercase tracking-widest">Awaiting Identity Input</p>
            </div>
          )}

          {loading && (
            <div className="py-24 text-center opacity-40 flex flex-col items-center">
              <Loader2 size={48} className="animate-spin mb-4" />
              <p className="font-mono text-[10px] uppercase tracking-[0.3em]">Archives Searching...</p>
            </div>
          )}

          {report && (
            <motion.div 
              initial={{ opacity: 0, scale: 0.98 }}
              animate={{ opacity: 1, scale: 1 }}
              className="space-y-8"
            >
              <div className="bg-[#141414] text-[#E4E3E0] p-6 shadow-[8px_8px_0px_0px_#E4E3E0] rounded-sm flex items-center justify-between">
                <div>
                  <h3 className="font-serif italic font-bold text-xl mb-1 flex items-center gap-2 underline decoration-amber-500 underline-offset-4 decoration-2">
                    Record Found: {report.report_id}
                  </h3>
                  <div className="flex gap-4 font-mono text-[9px] uppercase tracking-widest opacity-60">
                    <span className="flex items-center gap-1"><FileText size={10} /> {report.gem_type}</span>
                    <span className="flex items-center gap-1"><User size={10} /> {report.client_name}</span>
                  </div>
                </div>
                <button 
                  onClick={handlePrint}
                  className="bg-amber-600 text-white px-6 py-2 font-mono text-[10px] uppercase tracking-widest font-bold flex items-center gap-2 hover:bg-amber-700 transition-colors"
                >
                  <Printer size={14} /> Execute Reprint
                </button>
              </div>

              <div className="bg-white border border-[#141414] p-1 shadow-[8px_8px_0px_0px_#141414] overflow-hidden pointer-events-none opacity-80 scale-95 origin-top">
                <GemReportPrint report={report} ref={printRef} />
              </div>
            </motion.div>
          )}
        </div>
      </div>
    </div>
  );
}
